baseURL = "http://43.138.87.70:1313"
theme = "hugo-dead-simple"

languageCode = "en-us"
title = "MySiteTitle"

[[menu.main]]
	name = "Home"
	url = "/"
	weight = 1
	
[[menu.main]]
	name = "Blog" 
	url = "/blog/"
	weight = 2

[[menu.main]]
	name = "Post" 
	url = "/post/"
	weight = 2

[[menu.main]]
	name = "Tags"
	url = "/tags/"
	weight = 3
